---
# test_app application

#- name: print application_name
#  action: debug msg="{{ application_name }}"
  
- name: print test_app application_version
  action: debug msg="{{ application_version }}"
  
- name: print test_app port (expect 8080)
  action: debug msg="{{ port }}"
