---
#
# Application Default Variables
#   May be overriden by an application role's vars/main.yml file
#   e.g. automation/applications/<applicaiton>/vars/main.yml and/or
#        automation/applications/<application>/vars/<branch>.yml
#

#####################
#  DEPLOYMENT VARS
#####################

application: "{{ namespace }}"
application_name: "{{ application }}-{{ branch }}"

application_dir: "/apps/{{ application_name }}"
application_log_dir: "/apps/{{ application_name }}/logs"

application_prepared_file: "{{ application_dir }}/.ansible_prepared"
application_deployed_file: "{{ application_dir }}/.ansible_deployed"


#####################
#  PREPARATION VARS
#####################

application_user: "{{ namespace }}"
application_user_home: "/home/{{ application_user }}"
application_user_group: "nogroup"
application_user_shell: "/bin/bash"

